from __future__ import annotations

from typing import Any, Protocol


class BrokerClient(Protocol):
    """Protocol for broker clients used by the engine execution layer."""

    @property
    def account(self) -> str: ...

    def get_accounts(self) -> dict[str, Any]: ...
    def get_assets(self) -> dict[str, Any]: ...
    def get_positions(self) -> dict[str, Any]: ...
    def get_active_orders(self) -> dict[str, Any]: ...
    def get_inactive_orders(self, limit: int = 20) -> dict[str, Any]: ...
    def get_filled_orders(self, limit: int = 20) -> dict[str, Any]: ...
    def get_order(self, id: int | None = None, order_id: int | None = None) -> dict[str, Any]: ...
    def get_transactions(self, order_id: int | None = None, symbol: str | None = None, limit: int = 50) -> dict[str, Any]: ...
    def get_market_state(self, market: str) -> dict[str, Any]: ...
    def get_quote_permission(self) -> dict[str, Any]: ...
    def get_delay_quotes(self, symbols: list[str], market: str | None = None) -> dict[str, Any]: ...
    def get_briefs(self, symbols: list[str], market: str | None = None) -> dict[str, Any]: ...
    def get_bars(self, symbols: list[str], period: str = "30min", limit: int = 30, begin_time: str | None = None, end_time: str | None = None) -> dict[str, Any]: ...
    def get_contract(self, symbol: str, market: str) -> dict[str, Any]: ...
    def create_order_no(self) -> dict[str, Any]: ...
    def preview_order(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def place_order(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def cancel_order(self, id: int | None = None, order_id: int | None = None) -> dict[str, Any]: ...
