from __future__ import annotations

from typing import Any, Protocol


class BrokerClient(Protocol):
    """Protocol for dashboard broker clients."""

    @property
    def account(self) -> str: ...

    def get_account_type(self) -> dict[str, Any]: ...
    def get_account_info(self) -> dict[str, Any]: ...
    def get_positions(self) -> list[dict[str, Any]]: ...
    def get_orders(self) -> list[dict[str, Any]]: ...
    def get_filled_orders(self) -> list[dict[str, Any]]: ...
    def get_today_transactions(self) -> list[dict[str, Any]]: ...
    def get_quote(self, symbols: list[str], market: str = "US") -> list[dict[str, Any]]: ...
    def get_market_status(self, market: str = "US") -> dict[str, Any]: ...
